defaults: &defaults
  :secret_token: please_change_me_because_i_m_not_safe

development:
  # we are using standard YML inheritance here, very powerful and native !
  <<: *defaults
  :secret_token: i_am_overrided

test:
  <<: *defaults

production:
  <<: *defaults